/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#fbf9f8",
        surface: "#fbf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "surface-container": "#efeded",
        "surface-container-high": "#e9e8e7",
        "surface-container-highest": "#e4e2e2",
        "surface-variant": "#e4e2e2",
        "surface-dim": "#dbdad9",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#57423d",
        "on-background": "#1b1c1c",
        outline: "#8b716b",
        "outline-variant": "#dec0b9",
        primary: "#a63b21",
        "on-primary": "#ffffff",
        "primary-container": "#e86b4d",
        "on-primary-container": "#560d00",
        secondary: "#5f5e5e",
        "secondary-container": "#e5e2e1",
        tertiary: "#5d5e60",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-surface": "#303031",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        base: "4px", xs: "8px", sm: "16px", md: "24px", lg: "32px", xl: "48px",
        gutter: "24px",
      },
      fontFamily: { sans: ["Manrope", "system-ui", "sans-serif"] },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px" }],
        "body-md": ["16px", { lineHeight: "24px" }],
        "body-sm": ["14px", { lineHeight: "20px" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
